# Generated by Django 5.2.6 on 2025-10-03 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nanoscope',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idsid', models.CharField(max_length=50)),
                ('trace_id', models.CharField(max_length=500)),
                ('span_id', models.CharField(max_length=500)),
                ('instance_id', models.CharField(max_length=500)),
                ('stat_us', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('download_url', models.TextField()),
                ('function_name', models.CharField(max_length=100)),
                ('time_stmp', models.CharField(max_length=100)),
                ('versions', models.TextField()),
                ('project_name', models.CharField(max_length=100)),
                ('stepping', models.CharField(max_length=100)),
                ('tool_name', models.CharField(max_length=100)),
                ('testid', models.CharField(max_length=100)),
                ('testname', models.CharField(max_length=500)),
                ('mapping', models.CharField(max_length=500)),
                ('events_covered', models.CharField(max_length=500)),
                ('test_purpose', models.TextField()),
                ('test_config_cmd', models.TextField()),
                ('test_result', models.CharField(max_length=100)),
                ('eventid', models.CharField(max_length=100)),
                ('event_description', models.TextField()),
                ('step_id', models.CharField(max_length=100)),
                ('step_description', models.TextField()),
                ('step_result', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Nanoscope',
                'managed': False,
            },
        ),
    ]
