# Generated by Django 5.2.6 on 2025-10-17 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='nanoscope',
            table='nanoscope',
        ),
    ]
